/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ZiA4UCscxQF
 */
import { CarouselItem, CarouselContent, CarouselPrevious, CarouselNext, Carousel } from "@/components/ui/carousel"

export function GallerySlider() {
  return (
    (<Carousel className="w-full max-w-sm">
      <CarouselContent className="h-[200px]">
        <CarouselItem>
          <div className="aspect-w-1 aspect-h-1 p-1">
            <img
              className="rounded-xl object-cover"
              height="300"
              src="/placeholder.svg"
              style={{
                aspectRatio: "300/300",
                objectFit: "cover",
              }}
              width="300" />
          </div>
        </CarouselItem>
        <CarouselItem>
          <div className="aspect-w-1 aspect-h-1 p-1">
            <img
              className="rounded-xl object-cover"
              height="300"
              src="/placeholder.svg"
              style={{
                aspectRatio: "300/300",
                objectFit: "cover",
              }}
              width="300" />
          </div>
        </CarouselItem>
        <CarouselItem>
          <div className="aspect-w-1 aspect-h-1 p-1">
            <img
              className="rounded-xl object-cover"
              height="300"
              src="/placeholder.svg"
              style={{
                aspectRatio: "300/300",
                objectFit: "cover",
              }}
              width="300" />
          </div>
        </CarouselItem>
        <CarouselItem>
          <div className="aspect-w-1 aspect-h-1 p-1">
            <img
              className="rounded-xl object-cover"
              height="300"
              src="/placeholder.svg"
              style={{
                aspectRatio: "300/300",
                objectFit: "cover",
              }}
              width="300" />
          </div>
        </CarouselItem>
        <CarouselItem>
          <div className="aspect-w-1 aspect-h-1 p-1">
            <img
              className="rounded-xl object-cover"
              height="300"
              src="/placeholder.svg"
              style={{
                aspectRatio: "300/300",
                objectFit: "cover",
              }}
              width="300" />
          </div>
        </CarouselItem>
        <CarouselItem>
          <div className="aspect-w-1 aspect-h-1 p-1">
            <img
              className="rounded-xl object-cover"
              height="300"
              src="/placeholder.svg"
              style={{
                aspectRatio: "300/300",
                objectFit: "cover",
              }}
              width="300" />
          </div>
        </CarouselItem>
      </CarouselContent>
      <CarouselPrevious />
      <CarouselNext />
    </Carousel>)
  );
}
